### ISSUE TITLE
Add 5 bulletpoints

### ISSUE THREAD

**Issue by ricleichtung** [udbhav/adhoc#29]
below the three breaking/favorites/features windows of the most recent posts with that tag

**Comment by udbhav** [comment]
Those aren't showing up because there aren't any stories with those tags that haven't already been put in the 3 main feature boxes.  You'll start seeing this when you put more content in.

**Comment by ricleichtung** [comment]
AHHHHH no wonder. thanks!

Ric Leichtung
Ad Hoc Founder
957 Broadway Fl. 2 // Brooklyn, NY 11221

AIM: ricdleichtung
Tw: @ricleichtung http://twitter.com/ricleichtung
Cell: 415-637-2056
http://internationaltapes.com/

On Mon, Apr 9, 2012 at 10:14 AM, Udbhav Gupta <
reply@reply.github.com
