### ISSUE TITLE
#36 Staff List

### ISSUE THREAD

**Issue by mattsullivan89** [udbhav/adhoc#36]
"Matt Sullivan" and "Staff Writer" should be flipped; extraneous space in between "Contributing Blogs" and the blogs themselves.

**Comment by udbhav** [comment]
About page can be changed in the admin by Emilie or Ric.

On Tue, Apr 10, 2012 at 3:15 PM, mattsullivan89 <
reply@reply.github.com

**Comment by mattsullivan89** [comment]
Cool, thanks for the tip
