### ISSUE TITLE
Editing posts in the CMS on Android and iPhone

### ISSUE THREAD

**Issue by ricleichtung** [udbhav/adhoc#6]
would be AMAZING.

**Comment by udbhav** [comment]
If you visit the admin with an iphone and/or android you'll see a plain text box and will be editing raw html.

**Comment by ricleichtung** [comment]
Got it, thanks!

Ric Leichtung
Sent from 415-637-2056
On Mar 26, 2012 8:50 PM, "Udbhav Gupta" <
reply@reply.github.com>
wrote:
